/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSelectRoomRouteImport } from './routes/_authenticated.select-room'
import { Route as AuthenticatedRegistrationRouteImport } from './routes/_authenticated.registration'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPaymentRouteImport } from './routes/_authenticated.payment'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated.documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBookRouteImport } from './routes/_authenticated.book'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated.announcements'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSelectRoomRoute = AuthenticatedSelectRoomRouteImport.update({
  id: '/select-room',
  path: '/select-room',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegistrationRoute =
  AuthenticatedRegistrationRouteImport.update({
    id: '/registration',
    path: '/registration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentRoute = AuthenticatedPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookRoute = AuthenticatedBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/book': typeof AuthenticatedBookRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/payment': typeof AuthenticatedPaymentRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/registration': typeof AuthenticatedRegistrationRoute
  '/select-room': typeof AuthenticatedSelectRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/book': typeof AuthenticatedBookRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/payment': typeof AuthenticatedPaymentRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/registration': typeof AuthenticatedRegistrationRoute
  '/select-room': typeof AuthenticatedSelectRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/book': typeof AuthenticatedBookRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/payment': typeof AuthenticatedPaymentRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/registration': typeof AuthenticatedRegistrationRoute
  '/_authenticated/select-room': typeof AuthenticatedSelectRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/announcements'
    | '/book'
    | '/dashboard'
    | '/documents'
    | '/payment'
    | '/profile'
    | '/registration'
    | '/select-room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/announcements'
    | '/book'
    | '/dashboard'
    | '/documents'
    | '/payment'
    | '/profile'
    | '/registration'
    | '/select-room'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/announcements'
    | '/_authenticated/book'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/payment'
    | '/_authenticated/profile'
    | '/_authenticated/registration'
    | '/_authenticated/select-room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/select-room': {
      id: '/_authenticated/select-room'
      path: '/select-room'
      fullPath: '/select-room'
      preLoaderRoute: typeof AuthenticatedSelectRoomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registration': {
      id: '/_authenticated/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof AuthenticatedRegistrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment': {
      id: '/_authenticated/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AuthenticatedPaymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/book': {
      id: '/_authenticated/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AuthenticatedBookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedBookRoute: typeof AuthenticatedBookRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedPaymentRoute: typeof AuthenticatedPaymentRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRegistrationRoute: typeof AuthenticatedRegistrationRoute
  AuthenticatedSelectRoomRoute: typeof AuthenticatedSelectRoomRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedBookRoute: AuthenticatedBookRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedPaymentRoute: AuthenticatedPaymentRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRegistrationRoute: AuthenticatedRegistrationRoute,
  AuthenticatedSelectRoomRoute: AuthenticatedSelectRoomRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
